// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar structure for Physical AI & Humanoid Robotics book
  physicalAIRoboticsSidebar: [
    {
      type: 'category',
      label: 'Physical AI & Humanoid Robotics',
      collapsed: false,
      items: [
        'intro',
        {
          type: 'category',
          label: 'Module 1: The Robotic Nervous System (ROS 2)',
          collapsed: false,
          items: [
            'module-1/intro-to-robot-middleware',
            'module-1/ros2-nodes-topics-services',
            'module-1/bridging-ai-agents-ros2',
            'module-1/urdf-anatomy-humanoid'
          ]
        },
        {
          type: 'category',
          label: 'Module 2: The Digital Twin (Gazebo)',
          collapsed: false,
          items: [
            'module-2/gazebo-vs-unity-comparison',
            'module-2/physics-gravity-collisions',
            'module-2/humanoid-simulation-gazebo',
            'module-2/visualization-rendering'
          ]
        },
        {
          type: 'category',
          label: 'Module 3: Navigation for Humanoids (Nav2)',
          collapsed: false,
          items: [
            'module-3/nav2-path-planning',
            'module-3/humanoid-movement-constraints',
            'module-3/bipedal-navigation',
            'module-3/foot-placement-planning'
          ]
        },
        {
          type: 'category',
          label: 'Module 4: Vision-Language-Action (VLA)',
          collapsed: false,
          items: [
            'module-4/voice-to-action-whisper',
            'module-4/llm-cognitive-planning',
            'module-4/vla-capstone-project',
            'module-4/integration-workflow'
          ]
        }
      ]
    }
  ]
};

export default sidebars;
